# This file contains configuration values to use in the github action.
# For local development you may or may not want somewhat different
# options.

# options for analysis running
run:
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

# all available settings of specific linters
linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stderr)
      - (bytes.Buffer).Write
      - (bytes.Buffer).WriteByte
      - (bytes.Buffer).WriteRune
      - (bytes.Buffer).WriteString
      - fmt.Fprintln(os.Stderr)

  gofmt:
    # simplify code: gofmt with `-s` option
    simplify: true

  govet:
    enable-all: true
    disable:
      - shadow

  goimports:
    local-prefixes: github.com/martian-lang/martian
  lll:
    line-length: 110
    tab-width: 4
  misspell:
    locale: US
    ignore-words:
      - pipestance
      - marsoc
  unused:
    exported-fields-are-used: true

linters:
  enable:
    - godot
    - gofmt
    - lll
    - prealloc
    - misspell
    - unconvert
    - unparam
    - unused
    - whitespace
