version: 2
updates:
- package-ecosystem: npm
  directory: "/web/martian"
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  versioning-strategy: increase-if-necessary
- package-ecosystem: npm
  directory: "/tools/syntax/vscode"
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  versioning-strategy: increase-if-necessary
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 1
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
