// Code generated by mro2go testdata/pipeline_stages.mro; DO NOT EDIT.

package main

// A structure to encode and decode args to the SUM_SQUARE_PIPELINE pipeline.
type SumSquarePipelineArgs struct {
	Values    []float64 `json:"values"`
	DisableSq bool      `json:"disable_sq"`
}

// CallName returns the name of this pipeline as defined in the .mro file.
func (*SumSquarePipelineArgs) CallName() string {
	return "SUM_SQUARE_PIPELINE"
}

// MroFileName returns the name of the .mro file which defines this pipeline.
func (*SumSquarePipelineArgs) MroFileName() string {
	return "testdata/pipeline_stages.mro"
}
