// Code generated by mro2go testdata/pipeline_stages.mro; DO NOT EDIT.

package main

// A structure to encode and decode args to the SUM_SQUARE_PIPELINE pipeline.
type SumSquarePipelineArgs struct {
	Values    []float64 `json:"values"`
	DisableSq bool      `json:"disable_sq"`
}
