#!/bin/bash

# MARIO-specific parameters
#-----------------------------------------------------------------
# __schedcmd__ = "qsub"
# __env__ = "SGE_ROOT" "path/to/sge/root"
# __env__ = "SGE_CLUSTER_NAME" "SGE cluster name"
# __env__ = "SGE_CELL" "usually 'default'"

# SGE-specific parameters
#-----------------------------------------------------------------
#$ -N <job_name>
#$ -V
#$ -pe threads <threads>
#$ -l h_vmem=<mem_gb>G
#$ -cwd
#$ -o <stdout>
#$ -e <stderr>

<cmd>
