<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>mro</string>
    </array>
    <key>name</key>
    <string>Martianlang</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>match</key>
        <string>^\s*(@include)\s+("(?:[^"]|\\")+")</string>
        <key>name</key>
        <string>meta.preprocessor.mro.import</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.import.mro</string>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string</string>
              </dict>
            </array>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>include</key>
        <string>#filetype</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#callable</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#pipeline_calls</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#call</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\#.*$</string>
            <key>name</key>
            <string>comment.line</string>
          </dict>
        </array>
      </dict>
      <key>string</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(")((?:[^\\"]|\\.)*)(")</string>
            <key>name</key>
            <string>string.quoted.double.mro</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.mro</string>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>\\(?:[0-7]{3}|[abfnrtv\\"]|x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4}|U[0-9a-fA-F]{8})</string>
                    <key>name</key>
                    <string>constant.character.escape.mro</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>\\(?:[0-7]+[^0-7]|[xuU][0-9a-fA-F]*[^0-9a-fA-F]|.)</string>
                    <key>name</key>
                    <string>invalid.illegal.unknown-escape.mro</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>[^\\"]</string>
                    <key>name</key>
                    <string>string.quoted.double.character.mro</string>
                  </dict>
                </array>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.mro</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>number</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b-?[0-9]+(:?\.[0-9]+[eE][+-]?|[eE][+-]?|\.)[0-9]+\b</string>
            <key>name</key>
            <string>constant.numeric.floating-point</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b-?0*[0-9]{1,19}\b</string>
            <key>name</key>
            <string>constant.numeric.integer</string>
          </dict>
        </array>
      </dict>
      <key>constant</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(true|false|null)\b</string>
            <key>name</key>
            <string>constant.language.mro</string>
          </dict>
        </array>
      </dict>
      <key>filetype_name</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?:[a-zA-z0-9_]+\.)*[a-zA-z0-9_]+</string>
            <key>name</key>
            <string>entity.name.type.mro.filetype</string>
          </dict>
        </array>
      </dict>
      <key>filetype</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.type.mro.filetype</string>
            <key>match</key>
            <string>^\s*(filetype)\s+((?:[a-zA-z0-9_]+\.)*[a-zA-z0-9_]+)\s*(;)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.type.mro.filetype</string>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#filetype_name</string>
                  </dict>
                </array>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.terminator.semicolon</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>binding_path</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.group.binding_path</string>
            <key>begin</key>
            <string>\b(?:(self)|(_?[a-zA-Z][a-zA-z0-9_]*))\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.language.mro.self</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.function</string>
              </dict>
            </dict>
            <key>end</key>
            <string>,</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.other.comma</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>meta.group.mro.member</string>
                <key>match</key>
                <string>(\.)\s*(_?[a-zA-Z][a-zA-z0-9_]*)</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.accessor.period.mro</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>variable.other.member.mro</string>
                  </dict>
                </dict>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>binding</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.brackets.binding_array</string>
            <key>begin</key>
            <string>\[</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.begin.bracket.square.mro</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\]</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.end.bracket.square.mro</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#binding</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.braces.binding_map</string>
            <key>begin</key>
            <string>{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.begin.bracket.curly.mro</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.end.bracket.curly.mro</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>meta.group.map_key_one_line</string>
                <key>match</key>
                <string>(?:("(?:[^"]|\\")*")|(_?[a-zA-Z][a-zA-z0-9_]*))\s*(:)\s*((?:"(?:[^"]|\\")*"|[^,:()"\[\]{}]*),?\s*$)</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#string</string>
                      </dict>
                    </array>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>variable.other.member.mro</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.other.colon.mro</string>
                  </dict>
                  <key>4</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#binding</string>
                      </dict>
                    </array>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>name</key>
                <string>meta.annotation.identifier.map_key</string>
                <key>begin</key>
                <string>(?:("(?:[^"]|\\")*")|(_?[a-zA-Z][a-zA-z0-9_]*))\s*(:)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#string</string>
                      </dict>
                    </array>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>variable.other.member.mro</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.other.colon.mro</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>,</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.other.comma</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#binding</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.annotation.identifier.simple_binding</string>
            <key>match</key>
            <string>("(?:[^"]|\\"\s*)*"|\b[^,:()"\[\]{}]*)(,)?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#constant</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#binding_path</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.other.comma</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>assignment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.function.parameters.assignment</string>
            <key>match</key>
            <string>\b(_?[a-zA-Z][a-zA-z0-9_]*)\s*(=)\s*(?:(split)\s+)?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.control.mro.split</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>call_modifier</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\blocal\b</string>
            <key>name</key>
            <string>variable.language.mro.local</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bpreflight\b</string>
            <key>name</key>
            <string>variable.language.mro.preflight</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bvolatile\b</string>
            <key>name</key>
            <string>variable.language.mro.volatile</string>
          </dict>
        </array>
      </dict>
      <key>call</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.function-call.mro</string>
            <key>begin</key>
            <string>\b(?:(map)\s+)?(call)((?:\s+(?:local|preflight|volatile)){0,3})\s+(_?[a-zA-Z][a-zA-z0-9_]*)\s+(as)\s+(_?[a-zA-Z][a-zA-z0-9_]*)\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.mro.map</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.control.mro.call</string>
              </dict>
              <key>3</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#call_modifier</string>
                  </dict>
                </array>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>variable.function</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>keyword.control.mro.as</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.alias</string>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.begin.bracket.round.mro</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.end.bracket.round.mro</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#assignment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#binding</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.function-call.mro</string>
            <key>begin</key>
            <string>\b(?:(map)\s+)?(call)((?:\s+(?:local|preflight|volatile)){0,3})\s+(_?[a-zA-Z][a-zA-z0-9_]*)\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.mro.map</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.control.mro.call</string>
              </dict>
              <key>3</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#call_modifier</string>
                  </dict>
                </array>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>entity.name.function</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.begin.bracket.round.mro</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.end.bracket.round.mro</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#assignment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#binding</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>pipeline_call</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#call</string>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.function.return-type.mro</string>
            <key>begin</key>
            <string>\b(return)\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.mro.return</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.begin.bracket.round.mro</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.end.bracket.round.mro</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#assignment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#binding</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.function.return-type.mro.retain</string>
            <key>begin</key>
            <string>\b(retain)\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.mro.retain</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.begin.bracket.round.mro</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.end.bracket.round.mro</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#binding_path</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.function.mro.using</string>
            <key>begin</key>
            <string>\b(using)\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.mro.using</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.begin.bracket.round.mro</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.end.bracket.round.mro</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>(preflight|local|volatile)\s*(=)\s*(true|false)\s*(,)</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <array>
                    <dict>
                      <key>patterns</key>
                      <array>
                        <dict>
                          <key>include</key>
                          <string>#call_modifier</string>
                        </dict>
                      </array>
                    </dict>
                  </array>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.assignment</string>
                  </dict>
                  <key>3</key>
                  <array>
                    <dict>
                      <key>include</key>
                      <string>#constant</string>
                    </dict>
                  </array>
                  <key>4</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.other.comma</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>match</key>
                <string>(disabled)\s*(=)\s*([a-zA-z0-9_.]+)\s*(,)</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>variable.language.mro.disabled</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.assignment</string>
                  </dict>
                  <key>3</key>
                  <array>
                    <dict>
                      <key>include</key>
                      <string>#binding_path</string>
                    </dict>
                  </array>
                  <key>4</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.other.comma</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>builtin_types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>storage.type.boolean</string>
            <key>match</key>
            <string>\bbool\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>storage.type.numeric.int</string>
            <key>match</key>
            <string>\bint\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>storage.type.numeric.float</string>
            <key>match</key>
            <string>\bfloat\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>storage.type.string</string>
            <key>match</key>
            <string>\b(?:string|file|path)\b</string>
          </dict>
        </array>
      </dict>
      <key>type_name</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.type.mro.typed_map</string>
            <key>begin</key>
            <string>\b(map)\s*(&lt;)\s*([a-zA-Z0-9._]*)\s*((?:\[\])*)\s*(&gt;)\s*((?:\[\])*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.map</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.generic.begin.bracket.angle.mro</string>
              </dict>
              <key>3</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#builtin_types</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#filetype_name</string>
                  </dict>
                </array>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>storage.modifier.array</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.generic.end.bracket.angle.mro</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>storage.modifier.array</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.type.mro.array</string>
            <key>match</key>
            <string>([a-zA-Z0-9._]*)\s*((?:\[\])*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#builtin_types</string>
                  </dict>
                  <dict>
                    <key>name</key>
                    <string>storage.type.map</string>
                    <key>match</key>
                    <string>\bmap\b</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#filetype_name</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>storage.modifier.array</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>param</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.function.parameters.mro.inparam</string>
            <key>match</key>
            <string>\b(in)\s*([a-zA-Z0-9._&lt;&gt;\[\]]*)\s+(_?[a-zA-Z][a-zA-z0-9_]*)(?:\s+("(?:[^"]|\\")*"))?\s*(,)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.modifier.mro.in</string>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#type_name</string>
                  </dict>
                </array>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.parameter</string>
              </dict>
              <key>4</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#string</string>
                  </dict>
                </array>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.other.comma</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.function.parameters.mro.outparam</string>
            <key>match</key>
            <string>\b(out)\s*([a-zA-Z0-9._&lt;&gt;\[\]]*)\s+(_?[a-zA-Z][a-zA-z0-9_]*)(?:\s+("(?:[^"]|\\")*")(?:\s+("(?:[^"]|\\")*"))?)?\s*(,)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.modifier.mro.out</string>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#type_name</string>
                  </dict>
                </array>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.parameter</string>
              </dict>
              <key>4</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#string</string>
                  </dict>
                </array>
              </dict>
              <key>5</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#string</string>
                  </dict>
                </array>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>punctuation.other.comma</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>callable</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.function.mro.pipeline</string>
            <key>begin</key>
            <string>\b(pipeline)\s+(_?[a-zA-Z][a-zA-z0-9_]*)\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.function.mro.pipeline</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.begin.bracket.round.mro</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.end.bracket.round.mro</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#param</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.function.mro.stage</string>
            <key>begin</key>
            <string>\b(stage)\s+(_?[a-zA-Z][a-zA-z0-9_]*)\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.function.mro.stage</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.begin.bracket.round.mro</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.end.bracket.round.mro</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#param</string>
              </dict>
              <dict>
                <key>name</key>
                <string>meta.function.parameters.mro.srcparam</string>
                <key>match</key>
                <string>\b(src)\s*(py|exec|comp)\s+("(?:[^"]|\\")+")\s*(,)</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>storage.modifier.mro.src</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.language.mro.srclang</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#string</string>
                      </dict>
                    </array>
                  </dict>
                  <key>4</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.other.comma</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.function.mro.split</string>
            <key>begin</key>
            <string>\b(split)\s*(?:using\s*)?(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.mro.split</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.begin.bracket.round.mro</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.end.bracket.round.mro</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#param</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.function.mro.using</string>
            <key>begin</key>
            <string>\b(using)\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.mro.using</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.begin.bracket.round.mro</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.end.bracket.round.mro</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>(threads|v?mem_?gb)\s*(=)\s*([0-9.eE+-]+)\s*(,)</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>variable.language.mro.resources</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.assignment</string>
                  </dict>
                  <key>3</key>
                  <array>
                    <dict>
                      <key>include</key>
                      <string>#number</string>
                    </dict>
                  </array>
                  <key>4</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.other.comma</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>match</key>
                <string>(special)\s*(=)\s*("(?:[^\\"]|\\.)*")\s*(,)</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>variable.language.mro.resources.special</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.assignment</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#string</string>
                      </dict>
                    </array>
                  </dict>
                  <key>4</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.other.comma</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>match</key>
                <string>(volatile)\s*(=)\s*(true|false|strict)\s*(,)</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>variable.language.mro.volatile</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.assignment</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>constant.language.mro</string>
                  </dict>
                  <key>4</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.other.comma</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.function.return-type.mro.retain</string>
            <key>begin</key>
            <string>\b(retain)\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.mro.retain</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.begin.bracket.round.mro</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.end.bracket.round.mro</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#binding_path</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.struct.mro</string>
            <key>begin</key>
            <string>\b(struct)\s+(_?[a-zA-Z][a-zA-z0-9_]*)\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.struct.mro</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.struct.mro</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.begin.bracket.round.mro</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.end.bracket.round.mro</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>meta.function.parameters.param</string>
                <key>match</key>
                <string>\b([a-zA-Z0-9._&lt;&gt;\[\]]*)\s+(_?[a-zA-Z][a-zA-z0-9_]*)(?:\s+("(?:[^"]|\\")*"))?(?:\s+("(?:[^"]|\\")*"))?\s*(,)</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#type_name</string>
                      </dict>
                    </array>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>variable.other.member.mro</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#string</string>
                      </dict>
                    </array>
                  </dict>
                  <key>4</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#string</string>
                      </dict>
                    </array>
                  </dict>
                  <key>5</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.other.comma</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>pipeline_calls</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.block.mro.pipeline</string>
            <key>begin</key>
            <string>{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.begin.bracket.curley.mro</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.end.bracket.curley.mro</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#pipeline_call</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.martianlang</string>
    <key>uuid</key>
    <string>5da873b6-8693-47c9-b074-1eb3574281d1</string>
  </dict>
</plist>