// Code generated by goyacc -l -p mm -o grammar.go grammar.y. DO NOT EDIT.
//
// Copyright (c) 2014 10X Genomics, Inc. All rights reserved.
//
// MRO grammar.
//

package syntax

import __yyfmt__ "fmt"

import (
	"strings"
)

type mmSymType struct {
	yys       int
	global    *Ast
	srcfile   *SourceFile
	arr       int16
	loc       int
	val       []byte
	modifiers *Modifiers
	dec       Dec
	decs      []Dec
	inparam   *InParam
	outparam  *OutParam
	s_member  *StructMember
	retains   []*RetainParam
	stretains *RetainParams
	i_params  *InParams
	o_params  *OutParams
	s_members []*StructMember
	res       *Resources
	par_tuple paramsTuple
	src       *SrcParam
	type_id   TypeId
	exp       Exp
	exps      []Exp
	rexp      *RefExp
	vexp      ValExp
	kvpairs   map[string]Exp
	call      *CallStm
	calls     []*CallStm
	binding   *BindStm
	bindings  *BindStms
	retstm    *ReturnStm
	plretains *PipelineRetains
	reflist   []*RefExp
	includes  []*Include
	intern    *stringIntern
}

const SKIP = 57346
const COMMENT = 57347
const INVALID = 57348
const INCLUDE_DIRECTIVE = 57349
const STAGE = 57350
const PIPELINE = 57351
const CALL = 57352
const RETURN = 57353
const IN = 57354
const OUT = 57355
const SRC = 57356
const AS = 57357
const FILETYPE = 57358
const MAP = 57359
const INT = 57360
const STRING = 57361
const FLOAT = 57362
const PATH = 57363
const BOOL = 57364
const SPLIT = 57365
const USING = 57366
const RETAIN = 57367
const LOCAL = 57368
const PREFLIGHT = 57369
const VOLATILE = 57370
const DISABLED = 57371
const STRICT = 57372
const STRUCT = 57373
const THREADS = 57374
const MEM_GB = 57375
const VMEM_GB = 57376
const SPECIAL = 57377
const ID = 57378
const LITSTRING = 57379
const NUM_FLOAT = 57380
const NUM_INT = 57381
const PY = 57382
const EXEC = 57383
const COMPILED = 57384
const SELF = 57385
const TRUE = 57386
const FALSE = 57387
const NULL = 57388
const DEFAULT = 57389

var mmToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"SKIP",
	"COMMENT",
	"INVALID",
	"';'",
	"':'",
	"','",
	"'='",
	"'.'",
	"'['",
	"']'",
	"'('",
	"')'",
	"'{'",
	"'}'",
	"'<'",
	"'>'",
	"INCLUDE_DIRECTIVE",
	"STAGE",
	"PIPELINE",
	"CALL",
	"RETURN",
	"IN",
	"OUT",
	"SRC",
	"AS",
	"FILETYPE",
	"MAP",
	"INT",
	"STRING",
	"FLOAT",
	"PATH",
	"BOOL",
	"SPLIT",
	"USING",
	"RETAIN",
	"LOCAL",
	"PREFLIGHT",
	"VOLATILE",
	"DISABLED",
	"STRICT",
	"STRUCT",
	"THREADS",
	"MEM_GB",
	"VMEM_GB",
	"SPECIAL",
	"ID",
	"LITSTRING",
	"NUM_FLOAT",
	"NUM_INT",
	"PY",
	"EXEC",
	"COMPILED",
	"SELF",
	"TRUE",
	"FALSE",
	"NULL",
	"DEFAULT",
}
var mmStatenames = [...]string{}

const mmEofCode = 1
const mmErrCode = 2
const mmInitialStackSize = 16

var mmExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 77,
	14, 141,
	28, 141,
	-2, 83,
	-1, 78,
	14, 144,
	28, 144,
	-2, 84,
	-1, 79,
	14, 152,
	28, 152,
	-2, 85,
}

const mmPrivate = 57344

const mmLast = 843

var mmAct = [...]int{

	63, 133, 146, 62, 154, 4, 243, 113, 31, 33,
	225, 201, 179, 23, 21, 134, 135, 139, 40, 117,
	116, 60, 15, 138, 287, 69, 126, 120, 70, 71,
	72, 22, 103, 25, 26, 24, 73, 286, 76, 80,
	193, 194, 195, 285, 39, 288, 108, 238, 45, 68,
	223, 200, 219, 178, 74, 52, 56, 50, 46, 49,
	57, 43, 53, 54, 55, 47, 48, 51, 41, 12,
	10, 11, 36, 44, 42, 64, 25, 26, 16, 107,
	289, 244, 127, 101, 248, 35, 40, 106, 202, 234,
	109, 180, 202, 265, 180, 218, 40, 236, 136, 137,
	141, 142, 114, 8, 227, 102, 129, 130, 131, 132,
	9, 148, 104, 111, 112, 140, 40, 149, 152, 270,
	235, 175, 174, 266, 267, 268, 269, 38, 32, 27,
	28, 8, 282, 99, 97, 136, 151, 17, 9, 141,
	153, 141, 7, 175, 40, 89, 34, 100, 98, 40,
	272, 160, 29, 90, 40, 165, 164, 160, 166, 261,
	177, 175, 186, 136, 188, 182, 170, 171, 176, 141,
	169, 175, 229, 34, 87, 254, 40, 198, 183, 184,
	185, 181, 88, 187, 140, 199, 203, 263, 210, 187,
	191, 141, 190, 213, 159, 196, 197, 152, 257, 255,
	250, 249, 245, 212, 211, 226, 45, 165, 164, 221,
	168, 222, 162, 52, 56, 50, 46, 49, 57, 43,
	53, 54, 55, 47, 48, 51, 41, 95, 94, 93,
	242, 44, 42, 239, 246, 241, 83, 105, 75, 204,
	84, 27, 28, 8, 251, 182, 136, 256, 253, 17,
	9, 22, 59, 81, 260, 24, 82, 82, 259, 143,
	86, 85, 271, 281, 29, 276, 274, 280, 45, 279,
	278, 277, 167, 161, 158, 52, 56, 50, 46, 49,
	57, 43, 53, 54, 55, 47, 48, 51, 41, 12,
	10, 11, 157, 44, 42, 64, 25, 26, 16, 22,
	156, 155, 294, 24, 293, 292, 291, 290, 284, 283,
	252, 240, 237, 232, 231, 230, 45, 228, 209, 208,
	207, 206, 205, 52, 56, 50, 46, 49, 57, 43,
	53, 54, 55, 47, 48, 51, 41, 12, 10, 11,
	145, 44, 42, 64, 25, 26, 16, 22, 144, 92,
	91, 24, 3, 61, 5, 30, 1, 258, 233, 96,
	128, 224, 66, 65, 45, 58, 14, 13, 172, 217,
	115, 189, 56, 50, 46, 49, 57, 43, 53, 54,
	55, 47, 48, 51, 41, 12, 10, 11, 150, 44,
	42, 64, 25, 26, 16, 262, 247, 264, 173, 147,
	20, 19, 45, 118, 121, 122, 124, 123, 125, 52,
	56, 50, 46, 49, 57, 43, 53, 54, 55, 47,
	48, 51, 41, 18, 37, 192, 119, 44, 42, 45,
	118, 121, 122, 124, 123, 125, 52, 56, 50, 46,
	49, 57, 43, 53, 54, 55, 47, 48, 51, 41,
	2, 0, 0, 0, 44, 42, 45, 0, 121, 122,
	124, 123, 125, 52, 56, 50, 46, 49, 57, 43,
	53, 54, 55, 47, 48, 51, 41, 0, 0, 214,
	0, 44, 42, 215, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 45, 0, 0, 0,
	0, 0, 0, 52, 56, 50, 46, 49, 57, 43,
	53, 54, 55, 47, 48, 51, 41, 273, 0, 0,
	0, 44, 42, 64, 0, 0, 0, 0, 0, 0,
	0, 45, 220, 0, 0, 0, 0, 0, 52, 56,
	50, 46, 49, 57, 43, 53, 54, 55, 47, 48,
	51, 41, 45, 0, 0, 0, 44, 42, 64, 52,
	56, 50, 46, 49, 57, 43, 53, 54, 55, 47,
	48, 51, 41, 180, 45, 0, 0, 44, 42, 0,
	0, 52, 56, 50, 46, 49, 57, 43, 53, 54,
	55, 47, 48, 51, 41, 67, 0, 0, 0, 44,
	42, 64, 0, 0, 0, 0, 0, 45, 0, 0,
	0, 0, 0, 0, 52, 56, 50, 46, 49, 57,
	43, 53, 54, 55, 47, 48, 51, 41, 68, 0,
	22, 0, 44, 42, 24, 0, 0, 0, 6, 27,
	28, 8, 0, 0, 0, 0, 0, 17, 9, 0,
	0, 0, 0, 0, 0, 0, 0, 275, 0, 0,
	0, 0, 29, 0, 0, 0, 0, 0, 12, 10,
	11, 45, 0, 0, 0, 25, 26, 16, 52, 56,
	50, 46, 49, 57, 43, 53, 54, 55, 47, 48,
	51, 41, 216, 0, 0, 0, 44, 42, 0, 0,
	0, 0, 0, 0, 0, 0, 45, 0, 0, 0,
	0, 0, 0, 52, 56, 50, 46, 49, 57, 43,
	53, 54, 55, 47, 48, 51, 41, 163, 0, 0,
	0, 44, 42, 0, 0, 0, 0, 0, 0, 0,
	0, 45, 0, 0, 0, 0, 0, 0, 52, 56,
	50, 46, 49, 57, 43, 53, 54, 55, 47, 48,
	51, 41, 110, 0, 0, 0, 44, 42, 0, 0,
	0, 0, 0, 0, 45, 0, 0, 0, 0, 0,
	0, 52, 56, 50, 46, 49, 57, 43, 53, 54,
	55, 47, 48, 51, 41, 45, 0, 0, 0, 44,
	42, 0, 52, 56, 50, 46, 49, 57, 43, 53,
	54, 55, 47, 48, 51, 41, 45, 0, 0, 0,
	44, 42, 0, 52, 56, 50, 77, 78, 79, 43,
	53, 54, 55, 47, 48, 51, 41, 0, 0, 0,
	0, 44, 42,
}
var mmPact = [...]int{

	618, -1000, 108, 220, 48, -1000, 22, -1000, -1000, 104,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 766, -1000, -1000,
	-1000, -1000, 239, -1000, 578, -1000, -1000, 766, 766, 766,
	220, 48, 4, 48, -1000, 224, -1000, 787, 766, 246,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 227, -1000,
	-1000, -1000, -1000, 250, 249, 165, 136, -1000, 342, 341,
	215, 214, 213, 48, -1000, -1000, 120, -1000, -1000, -1000,
	119, -1000, 766, 19, -1000, 177, 766, 29, -1000, 745,
	-1000, 287, 287, -1000, -1000, 400, 67, 766, 766, 766,
	766, -1000, -1000, -1000, 245, -1000, 248, 340, -1000, 332,
	-1000, -1000, -1000, 86, 86, 373, -1000, 766, 122, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 245, -1000, -1000, 291,
	290, 282, 264, 179, 766, -1000, 263, 198, 712, -1000,
	766, 262, 196, 766, 287, 287, 95, -1000, 400, 145,
	-1000, -1000, 44, 427, 233, -24, -24, -24, 545, -1000,
	-1000, 287, 766, -1000, -1000, -1000, -1000, 335, 766, 245,
	-1000, -1000, 175, -1000, -13, 400, 766, 169, -1000, 42,
	-1000, -1000, 226, 313, 312, 311, 310, 309, 173, 467,
	677, 59, 2, -1000, -1000, -1000, 523, -1000, 41, 80,
	-1000, 308, -1000, 153, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 306, 305, 304, 287, -1, -1000, 52, 83, 303,
	-1000, 38, 302, -1000, 80, 43, 48, 188, -1000, -1000,
	-1000, -1000, -1000, 46, 187, 186, -1000, -1000, -1000, 301,
	-1000, 43, 48, 158, 185, 766, 233, -1000, 184, -1000,
	-1000, 86, -1000, 142, -1000, -1000, 172, -1000, 78, 86,
	135, -1000, 502, -1000, 642, -1000, 261, 260, 259, 257,
	253, 117, -1000, -1000, 300, -1000, 299, -9, -15, -28,
	-5, 37, -1000, -1000, -1000, 298, 297, 296, 295, 293,
	-1000, -1000, -1000, -1000, -1000,
}
var mmPgo = [...]int{

	0, 450, 0, 26, 27, 426, 12, 425, 11, 424,
	4, 142, 423, 401, 400, 352, 399, 398, 20, 397,
	396, 395, 6, 7, 2, 370, 369, 368, 19, 21,
	3, 353, 22, 367, 14, 366, 13, 365, 363, 362,
	5, 361, 16, 17, 360, 1, 15, 23, 359, 10,
	358, 357, 356,
}
var mmR1 = [...]int{

	0, 52, 52, 52, 52, 52, 52, 52, 1, 1,
	15, 15, 11, 11, 11, 11, 13, 13, 12, 14,
	50, 50, 51, 51, 51, 51, 51, 51, 20, 20,
	19, 19, 3, 3, 10, 10, 23, 23, 16, 16,
	24, 24, 17, 17, 17, 17, 25, 25, 18, 18,
	18, 27, 6, 8, 5, 5, 4, 4, 4, 4,
	4, 4, 28, 28, 7, 7, 7, 26, 26, 26,
	49, 22, 22, 21, 21, 41, 41, 40, 40, 40,
	40, 40, 9, 9, 9, 9, 48, 48, 44, 44,
	44, 44, 46, 46, 45, 45, 47, 47, 47, 47,
	42, 43, 43, 43, 37, 37, 38, 38, 39, 39,
	29, 29, 31, 31, 31, 31, 31, 31, 31, 34,
	34, 33, 33, 36, 36, 35, 35, 35, 35, 32,
	32, 30, 30, 30, 30, 30, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2,
}
var mmR2 = [...]int{

	0, 2, 3, 2, 1, 2, 1, 1, 3, 2,
	2, 1, 3, 1, 1, 1, 11, 10, 10, 5,
	0, 4, 0, 5, 5, 5, 5, 5, 0, 4,
	0, 3, 3, 1, 0, 3, 0, 2, 5, 4,
	0, 2, 3, 4, 5, 2, 1, 2, 3, 4,
	5, 4, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 6, 2, 1, 1, 1, 0, 6, 5,
	4, 0, 4, 0, 3, 2, 1, 6, 8, 6,
	8, 5, 0, 2, 2, 2, 0, 2, 4, 4,
	4, 4, 2, 1, 1, 0, 1, 2, 2, 2,
	4, 5, 5, 5, 3, 1, 5, 3, 5, 3,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 3,
	4, 1, 2, 3, 4, 1, 3, 4, 2, 1,
	1, 3, 3, 1, 3, 5, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1,
}
var mmChk = [...]int{

	-1000, -52, -1, -15, -40, -31, 20, -11, 23, 30,
	51, 52, 50, -33, -35, -32, 59, 29, -12, -13,
	-14, -34, 12, -36, 16, 57, 58, 21, 22, 44,
	-15, -40, 20, -40, -11, 37, 50, -9, 23, -3,
	-2, 49, 55, 42, 54, 29, 39, 46, 47, 40,
	38, 48, 36, 43, 44, 45, 37, 41, -37, 13,
	-29, -31, -30, -2, 56, -38, -39, 17, 50, -2,
	-2, -2, -2, -40, 50, 14, -2, 39, 40, 41,
	-2, 7, 11, 9, 13, 11, 11, 9, 17, 9,
	17, 8, 8, 14, 14, 14, -48, 14, 28, 14,
	28, -2, -29, 13, -3, 60, -2, 50, 17, -2,
	17, -29, -29, -23, -23, -25, -18, -28, 30, -5,
	-4, 31, 32, 34, 33, 35, -3, 15, -44, 39,
	40, 41, 42, -45, -46, -42, -2, -2, -47, -43,
	-46, -2, -2, 11, 8, 8, -24, -16, 25, -24,
	15, -18, -2, 18, -10, 10, 10, 10, 10, 15,
	-42, 10, 14, 15, -43, -42, -43, 10, 14, -3,
	-29, -29, -27, -17, 27, 26, -28, 15, 9, -6,
	50, -4, 12, -32, -32, -32, -30, -29, -45, 36,
	-47, 15, -7, 53, 54, 55, -28, -18, -2, 16,
	9, -8, 50, -10, 13, 9, 9, 9, 9, 9,
	15, -34, -36, -30, 12, 16, 15, -26, 36, 50,
	9, -6, -6, 9, -41, -49, -40, 24, 9, 19,
	9, 9, 9, -50, 37, 37, 14, 9, 9, -8,
	9, -49, -40, -22, 38, 14, -10, -20, 38, 14,
	14, -23, 9, -22, 17, 14, -45, 14, -51, -23,
	-24, 17, -21, 15, -19, 15, 45, 46, 47, 48,
	41, -24, 15, 15, -30, 15, -2, 10, 10, 10,
	10, 10, 15, 9, 9, 52, 52, 52, 50, 43,
	9, 9, 9, 9, 9,
}
var mmDef = [...]int{

	0, -2, 0, 4, 6, 7, 0, 11, 82, 0,
	112, 113, 114, 115, 116, 117, 118, 0, 13, 14,
	15, 121, 0, 125, 0, 129, 130, 0, 0, 0,
	1, 3, 0, 5, 10, 0, 9, 0, 0, 0,
	33, 136, 137, 138, 139, 140, 141, 142, 143, 144,
	145, 146, 147, 148, 149, 150, 151, 152, 0, 122,
	105, 110, 111, 133, 0, 0, 0, 128, 0, 0,
	0, 0, 0, 2, 8, 86, 0, -2, -2, -2,
	0, 12, 0, 0, 119, 0, 0, 0, 123, 0,
	126, 0, 0, 36, 36, 0, 0, 95, 0, 0,
	0, 32, 104, 120, 131, 132, 134, 0, 124, 0,
	127, 107, 109, 40, 40, 0, 46, 0, 55, 34,
	54, 56, 57, 58, 59, 60, 61, 81, 87, 0,
	0, 0, 0, 0, 94, 93, 0, 0, 0, 96,
	0, 0, 0, 0, 0, 0, 0, 37, 0, 0,
	19, 47, 0, 0, 63, 0, 0, 0, 0, 77,
	92, 0, 95, 79, 98, 99, 97, 0, 0, 135,
	106, 108, 0, 41, 0, 0, 0, 0, 48, 0,
	52, 34, 0, 0, 0, 0, 0, 0, 0, 147,
	0, 67, 0, 64, 65, 66, 0, 45, 0, 0,
	49, 0, 53, 0, 35, 88, 89, 90, 91, 100,
	78, 0, 0, 0, 0, 0, 80, 20, 0, 0,
	42, 0, 0, 39, 0, 71, 76, 0, 50, 34,
	101, 102, 103, 28, 0, 0, 36, 51, 43, 0,
	38, 71, 75, 0, 0, 95, 62, 18, 0, 22,
	36, 40, 44, 0, 17, 73, 0, 30, 0, 40,
	0, 16, 0, 70, 0, 21, 0, 0, 0, 0,
	0, 0, 69, 72, 0, 29, 0, 0, 0, 0,
	0, 0, 68, 74, 31, 0, 0, 0, 0, 0,
	23, 24, 25, 26, 27,
}
var mmTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	14, 15, 3, 3, 9, 3, 11, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 8, 7,
	18, 10, 19, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 12, 3, 13, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 16, 3, 17,
}
var mmTok2 = [...]int{

	2, 3, 4, 5, 6, 20, 21, 22, 23, 24,
	25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
	35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
	45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
	55, 56, 57, 58, 59, 60,
}
var mmTok3 = [...]int{
	0,
}

var mmErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	mmDebug        = 0
	mmErrorVerbose = false
)

type mmLexer interface {
	Lex(lval *mmSymType) int
	Error(s string)
}

type mmParser interface {
	Parse(mmLexer) int
	Lookahead() int
}

type mmParserImpl struct {
	lval  mmSymType
	stack [mmInitialStackSize]mmSymType
	char  int
}

func (p *mmParserImpl) Lookahead() int {
	return p.char
}

func mmNewParser() mmParser {
	return &mmParserImpl{}
}

const mmFlag = -1000

func mmTokname(c int) string {
	if c >= 1 && c-1 < len(mmToknames) {
		if mmToknames[c-1] != "" {
			return mmToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func mmStatname(s int) string {
	if s >= 0 && s < len(mmStatenames) {
		if mmStatenames[s] != "" {
			return mmStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func mmErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !mmErrorVerbose {
		return "syntax error"
	}

	for _, e := range mmErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + mmTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := mmPact[state]
	for tok := TOKSTART; tok-1 < len(mmToknames); tok++ {
		if n := base + tok; n >= 0 && n < mmLast && mmChk[mmAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if mmDef[state] == -2 {
		i := 0
		for mmExca[i] != -1 || mmExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; mmExca[i] >= 0; i += 2 {
			tok := mmExca[i]
			if tok < TOKSTART || mmExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if mmExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += mmTokname(tok)
	}
	return res
}

func mmlex1(lex mmLexer, lval *mmSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = mmTok1[0]
		goto out
	}
	if char < len(mmTok1) {
		token = mmTok1[char]
		goto out
	}
	if char >= mmPrivate {
		if char < mmPrivate+len(mmTok2) {
			token = mmTok2[char-mmPrivate]
			goto out
		}
	}
	for i := 0; i < len(mmTok3); i += 2 {
		token = mmTok3[i+0]
		if token == char {
			token = mmTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = mmTok2[1] /* unknown char */
	}
	if mmDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", mmTokname(token), uint(char))
	}
	return char, token
}

func mmParse(mmlex mmLexer) int {
	return mmNewParser().Parse(mmlex)
}

func (mmrcvr *mmParserImpl) Parse(mmlex mmLexer) int {
	var mmn int
	var mmVAL mmSymType
	var mmDollar []mmSymType
	_ = mmDollar // silence set and not used
	mmS := mmrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	mmstate := 0
	mmrcvr.char = -1
	mmtoken := -1 // mmrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		mmstate = -1
		mmrcvr.char = -1
		mmtoken = -1
	}()
	mmp := -1
	goto mmstack

ret0:
	return 0

ret1:
	return 1

mmstack:
	/* put a state and value onto the stack */
	if mmDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", mmTokname(mmtoken), mmStatname(mmstate))
	}

	mmp++
	if mmp >= len(mmS) {
		nyys := make([]mmSymType, len(mmS)*2)
		copy(nyys, mmS)
		mmS = nyys
	}
	mmS[mmp] = mmVAL
	mmS[mmp].yys = mmstate

mmnewstate:
	mmn = mmPact[mmstate]
	if mmn <= mmFlag {
		goto mmdefault /* simple state */
	}
	if mmrcvr.char < 0 {
		mmrcvr.char, mmtoken = mmlex1(mmlex, &mmrcvr.lval)
	}
	mmn += mmtoken
	if mmn < 0 || mmn >= mmLast {
		goto mmdefault
	}
	mmn = mmAct[mmn]
	if mmChk[mmn] == mmtoken { /* valid shift */
		mmrcvr.char = -1
		mmtoken = -1
		mmVAL = mmrcvr.lval
		mmstate = mmn
		if Errflag > 0 {
			Errflag--
		}
		goto mmstack
	}

mmdefault:
	/* default state action */
	mmn = mmDef[mmstate]
	if mmn == -2 {
		if mmrcvr.char < 0 {
			mmrcvr.char, mmtoken = mmlex1(mmlex, &mmrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if mmExca[xi+0] == -1 && mmExca[xi+1] == mmstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			mmn = mmExca[xi+0]
			if mmn < 0 || mmn == mmtoken {
				break
			}
		}
		mmn = mmExca[xi+1]
		if mmn < 0 {
			goto ret0
		}
	}
	if mmn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			mmlex.Error(mmErrorMessage(mmstate, mmtoken))
			Nerrs++
			if mmDebug >= 1 {
				__yyfmt__.Printf("%s", mmStatname(mmstate))
				__yyfmt__.Printf(" saw %s\n", mmTokname(mmtoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for mmp >= 0 {
				mmn = mmPact[mmS[mmp].yys] + mmErrCode
				if mmn >= 0 && mmn < mmLast {
					mmstate = mmAct[mmn] /* simulate a shift of "error" */
					if mmChk[mmstate] == mmErrCode {
						goto mmstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if mmDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", mmS[mmp].yys)
				}
				mmp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if mmDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", mmTokname(mmtoken))
			}
			if mmtoken == mmEofCode {
				goto ret1
			}
			mmrcvr.char = -1
			mmtoken = -1
			goto mmnewstate /* try again in the same state */
		}
	}

	/* reduction by production mmn */
	if mmDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", mmn, mmStatname(mmstate))
	}

	mmnt := mmn
	mmpt := mmp
	_ = mmpt // guard against "declared and not used"

	mmp -= mmR2[mmn]
	// mmp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if mmp+1 >= len(mmS) {
		nyys := make([]mmSymType, len(mmS)*2)
		copy(nyys, mmS)
		mmS = nyys
	}
	mmVAL = mmS[mmp+1]

	/* consult goto table to find next state */
	mmn = mmR1[mmn]
	mmg := mmPgo[mmn]
	mmj := mmg + mmS[mmp].yys + 1

	if mmj >= mmLast {
		mmstate = mmAct[mmg]
	} else {
		mmstate = mmAct[mmj]
		if mmChk[mmstate] != -mmn {
			mmstate = mmAct[mmg]
		}
	}
	// dummy call; replaced with literal code
	switch mmnt {

	case 1:
		mmDollar = mmS[mmpt-2 : mmpt+1]
		{
			global := NewAst(mmDollar[2].decs, nil, mmDollar[2].srcfile)
			global.Includes = mmDollar[1].includes
			mmlex.(*mmLexInfo).global = global
		}
	case 2:
		mmDollar = mmS[mmpt-3 : mmpt+1]
		{
			global := NewAst(mmDollar[2].decs, mmDollar[3].call, mmDollar[2].srcfile)
			global.Includes = mmDollar[1].includes
			mmlex.(*mmLexInfo).global = global
		}
	case 3:
		mmDollar = mmS[mmpt-2 : mmpt+1]
		{
			global := NewAst(nil, mmDollar[2].call, mmDollar[2].srcfile)
			global.Includes = mmDollar[1].includes
			mmlex.(*mmLexInfo).global = global
		}
	case 4:
		mmDollar = mmS[mmpt-1 : mmpt+1]
		{
			global := NewAst(mmDollar[1].decs, nil, mmDollar[1].srcfile)
			mmlex.(*mmLexInfo).global = global
		}
	case 5:
		mmDollar = mmS[mmpt-2 : mmpt+1]
		{
			global := NewAst(mmDollar[1].decs, mmDollar[2].call, mmDollar[1].srcfile)
			mmlex.(*mmLexInfo).global = global
		}
	case 6:
		mmDollar = mmS[mmpt-1 : mmpt+1]
		{
			global := NewAst(nil, mmDollar[1].call, mmDollar[1].srcfile)
			mmlex.(*mmLexInfo).global = global
		}
	case 7:
		mmDollar = mmS[mmpt-1 : mmpt+1]
		{
			global := NewAst(nil, nil, mmDollar[1].srcfile)
			mmlex.(*mmLexInfo).global = global
			mmlex.(*mmLexInfo).exp = mmDollar[1].vexp
		}
	case 8:
		mmDollar = mmS[mmpt-3 : mmpt+1]
		{
			mmVAL.includes = append(mmDollar[1].includes, &Include{
				Node:  NewAstNode(mmDollar[2].loc, mmDollar[2].srcfile),
				Value: mmDollar[3].intern.unquote(mmDollar[3].val),
			})
		}
	case 9:
		mmDollar = mmS[mmpt-2 : mmpt+1]
		{
			mmVAL.includes = []*Include{
				{
					Node:  NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
					Value: mmDollar[2].intern.unquote(mmDollar[2].val),
				},
			}
		}
	case 10:
		mmDollar = mmS[mmpt-2 : mmpt+1]
		{
			mmVAL.decs = append(mmDollar[1].decs, mmDollar[2].dec)
		}
	case 11:
		mmDollar = mmS[mmpt-1 : mmpt+1]
		{
			mmVAL.decs = []Dec{mmDollar[1].dec}
		}
	case 12:
		mmDollar = mmS[mmpt-3 : mmpt+1]
		{
			mmVAL.dec = &UserType{
				Node: NewAstNode(mmDollar[2].loc, mmDollar[2].srcfile),
				Id:   mmDollar[2].intern.Get(mmDollar[2].val),
			}
		}
	case 16:
		mmDollar = mmS[mmpt-11 : mmpt+1]
		{
			mmVAL.dec = &Pipeline{
				Node:      NewAstNode(mmDollar[2].loc, mmDollar[2].srcfile),
				Id:        mmDollar[2].intern.Get(mmDollar[2].val),
				InParams:  mmDollar[4].i_params,
				OutParams: mmDollar[5].o_params,
				Calls:     mmDollar[8].calls,
				Ret:       mmDollar[9].retstm,
				Retain:    mmDollar[10].plretains,
			}
		}
	case 17:
		mmDollar = mmS[mmpt-10 : mmpt+1]
		{
			mmVAL.dec = &Pipeline{
				Node:      NewAstNode(mmDollar[2].loc, mmDollar[2].srcfile),
				Id:        mmDollar[2].intern.Get(mmDollar[2].val),
				InParams:  mmDollar[4].i_params,
				OutParams: mmDollar[5].o_params,
				Callables: new(Callables),
				Ret:       mmDollar[8].retstm,
				Retain:    mmDollar[9].plretains,
			}
		}
	case 18:
		mmDollar = mmS[mmpt-10 : mmpt+1]
		{
			mmVAL.dec = &Stage{
				Node:      NewAstNode(mmDollar[2].loc, mmDollar[2].srcfile),
				Id:        mmDollar[2].intern.Get(mmDollar[2].val),
				InParams:  mmDollar[4].i_params,
				OutParams: mmDollar[5].o_params,
				Src:       mmDollar[6].src,
				ChunkIns:  mmDollar[8].par_tuple.Ins,
				ChunkOuts: mmDollar[8].par_tuple.Outs,
				Split:     mmDollar[8].par_tuple.Present,
				Resources: mmDollar[9].res,
				Retain:    mmDollar[10].stretains,
			}
		}
	case 19:
		mmDollar = mmS[mmpt-5 : mmpt+1]
		{
			mmVAL.dec = &StructType{
				Node:    NewAstNode(mmDollar[2].loc, mmDollar[2].srcfile),
				Id:      mmDollar[2].intern.Get(mmDollar[2].val),
				Members: mmDollar[4].s_members,
			}
		}
	case 20:
		mmDollar = mmS[mmpt-0 : mmpt+1]
		{
			mmVAL.res = nil
		}
	case 21:
		mmDollar = mmS[mmpt-4 : mmpt+1]
		{
			mmDollar[3].res.Node = NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile)
			mmVAL.res = mmDollar[3].res
		}
	case 22:
		mmDollar = mmS[mmpt-0 : mmpt+1]
		{
			mmVAL.res = new(Resources)
		}
	case 23:
		mmDollar = mmS[mmpt-5 : mmpt+1]
		{
			n := NewAstNode(mmDollar[2].loc, mmDollar[2].srcfile)
			mmDollar[1].res.ThreadNode = &n
			i := parseInt(mmDollar[4].val)
			mmDollar[1].res.Threads = int16(i)
			mmVAL.res = mmDollar[1].res
		}
	case 24:
		mmDollar = mmS[mmpt-5 : mmpt+1]
		{
			n := NewAstNode(mmDollar[2].loc, mmDollar[2].srcfile)
			mmDollar[1].res.MemNode = &n
			i := parseInt(mmDollar[4].val)
			mmDollar[1].res.MemGB = int16(i)
			mmVAL.res = mmDollar[1].res
		}
	case 25:
		mmDollar = mmS[mmpt-5 : mmpt+1]
		{
			n := NewAstNode(mmDollar[2].loc, mmDollar[2].srcfile)
			mmDollar[1].res.VMemNode = &n
			i := parseInt(mmDollar[4].val)
			mmDollar[1].res.VMemGB = int16(i)
			mmVAL.res = mmDollar[1].res
		}
	case 26:
		mmDollar = mmS[mmpt-5 : mmpt+1]
		{
			n := NewAstNode(mmDollar[2].loc, mmDollar[2].srcfile)
			mmDollar[1].res.SpecialNode = &n
			mmDollar[1].res.Special = mmDollar[4].intern.unquote(mmDollar[4].val)
			mmVAL.res = mmDollar[1].res
		}
	case 27:
		mmDollar = mmS[mmpt-5 : mmpt+1]
		{
			n := NewAstNode(mmDollar[2].loc, mmDollar[2].srcfile)
			mmDollar[1].res.VolatileNode = &n
			mmDollar[1].res.StrictVolatile = true
			mmVAL.res = mmDollar[1].res
		}
	case 28:
		mmDollar = mmS[mmpt-0 : mmpt+1]
		{
			mmVAL.stretains = nil
		}
	case 29:
		mmDollar = mmS[mmpt-4 : mmpt+1]
		{
			mmVAL.stretains = &RetainParams{
				Node:   NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Params: mmDollar[3].retains,
			}
		}
	case 30:
		mmDollar = mmS[mmpt-0 : mmpt+1]
		{
			mmVAL.retains = nil
		}
	case 31:
		mmDollar = mmS[mmpt-3 : mmpt+1]
		{
			mmVAL.retains = append(mmDollar[1].retains, &RetainParam{
				Node: NewAstNode(mmDollar[2].loc, mmDollar[2].srcfile),
				Id:   mmDollar[2].intern.Get(mmDollar[2].val),
			})
		}
	case 32:
		mmDollar = mmS[mmpt-3 : mmpt+1]
		{
			mmVAL.val = append(append(mmDollar[1].val, '.'), mmDollar[3].val...)
		}
	case 33:
		mmDollar = mmS[mmpt-1 : mmpt+1]
		{
			// set capacity == length so append doesn't overwrite
			// other parts of the buffer later.
			mmVAL.val = mmDollar[1].val[:len(mmDollar[1].val):len(mmDollar[1].val)]
		}
	case 34:
		mmDollar = mmS[mmpt-0 : mmpt+1]
		{
			mmVAL.arr = 0
		}
	case 35:
		mmDollar = mmS[mmpt-3 : mmpt+1]
		{
			mmVAL.arr++
		}
	case 36:
		mmDollar = mmS[mmpt-0 : mmpt+1]
		{
			mmVAL.i_params = new(InParams)
		}
	case 37:
		mmDollar = mmS[mmpt-2 : mmpt+1]
		{
			mmDollar[1].i_params.List = append(mmDollar[1].i_params.List, mmDollar[2].inparam)
			mmVAL.i_params = mmDollar[1].i_params
		}
	case 38:
		mmDollar = mmS[mmpt-5 : mmpt+1]
		{
			mmVAL.inparam = &InParam{
				Node:  NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Tname: mmDollar[2].type_id,
				Id:    mmDollar[3].intern.Get(mmDollar[3].val),
				Help:  unquote(mmDollar[4].val),
			}
		}
	case 39:
		mmDollar = mmS[mmpt-4 : mmpt+1]
		{
			mmVAL.inparam = &InParam{
				Node:  NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Tname: mmDollar[2].type_id,
				Id:    mmDollar[3].intern.Get(mmDollar[3].val),
			}
		}
	case 40:
		mmDollar = mmS[mmpt-0 : mmpt+1]
		{
			mmVAL.o_params = new(OutParams)
		}
	case 41:
		mmDollar = mmS[mmpt-2 : mmpt+1]
		{
			mmDollar[1].o_params.List = append(mmDollar[1].o_params.List, mmDollar[2].outparam)
			mmVAL.o_params = mmDollar[1].o_params
		}
	case 42:
		mmDollar = mmS[mmpt-3 : mmpt+1]
		{
			mmVAL.outparam = &OutParam{
				StructMember: StructMember{
					Node:  NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
					Tname: mmDollar[2].type_id,
					Id:    defaultOutName,
				},
			}
		}
	case 43:
		mmDollar = mmS[mmpt-4 : mmpt+1]
		{
			mmVAL.outparam = &OutParam{
				StructMember: StructMember{
					Node:  NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
					Tname: mmDollar[2].type_id,
					Id:    defaultOutName,
					Help:  unquote(mmDollar[3].val),
				},
			}
		}
	case 44:
		mmDollar = mmS[mmpt-5 : mmpt+1]
		{
			mmVAL.outparam = &OutParam{
				StructMember: StructMember{
					Node:    NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
					Tname:   mmDollar[2].type_id,
					Id:      defaultOutName,
					OutName: mmDollar[5].intern.unquote(mmDollar[4].val),
					Help:    unquote(mmDollar[3].val),
				},
			}
		}
	case 45:
		mmDollar = mmS[mmpt-2 : mmpt+1]
		{
			mmVAL.outparam = &OutParam{
				StructMember: *mmDollar[2].s_member,
			}
		}
	case 46:
		mmDollar = mmS[mmpt-1 : mmpt+1]
		{
			mmVAL.s_members = []*StructMember{mmDollar[1].s_member}
		}
	case 47:
		mmDollar = mmS[mmpt-2 : mmpt+1]
		{
			mmVAL.s_members = append(mmDollar[1].s_members, mmDollar[2].s_member)
		}
	case 48:
		mmDollar = mmS[mmpt-3 : mmpt+1]
		{
			mmVAL.s_member = &StructMember{
				Node:  NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Tname: mmDollar[1].type_id,
				Id:    mmDollar[2].intern.Get(mmDollar[2].val),
			}
		}
	case 49:
		mmDollar = mmS[mmpt-4 : mmpt+1]
		{
			mmVAL.s_member = &StructMember{
				Node:  NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Tname: mmDollar[1].type_id,
				Id:    mmDollar[2].intern.Get(mmDollar[2].val),
				Help:  unquote(mmDollar[3].val),
			}
		}
	case 50:
		mmDollar = mmS[mmpt-5 : mmpt+1]
		{
			mmVAL.s_member = &StructMember{
				Node:    NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Tname:   mmDollar[1].type_id,
				Id:      mmDollar[2].intern.Get(mmDollar[2].val),
				OutName: mmDollar[4].intern.unquote(mmDollar[4].val),
				Help:    unquote(mmDollar[3].val),
			}
		}
	case 51:
		mmDollar = mmS[mmpt-4 : mmpt+1]
		{
			cmd := strings.TrimSpace(mmDollar[3].intern.unquote(mmDollar[3].val))
			stagecodeParts := strings.Fields(mmDollar[3].intern.unquote(mmDollar[3].val))
			mmVAL.src = &SrcParam{
				Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Lang: StageLanguage(mmDollar[2].intern.Get(mmDollar[2].val)),
				cmd:  cmd,
				Path: stagecodeParts[0],
				Args: stagecodeParts[1:],
			}
		}
	case 62:
		mmDollar = mmS[mmpt-6 : mmpt+1]
		{
			mmVAL.type_id = TypeId{
				Tname:    mmDollar[3].intern.Get(mmDollar[3].val),
				ArrayDim: mmDollar[6].arr,
				MapDim:   1 + mmDollar[4].arr,
			}
		}
	case 63:
		mmDollar = mmS[mmpt-2 : mmpt+1]
		{
			mmVAL.type_id = TypeId{
				Tname:    mmDollar[1].intern.Get(mmDollar[1].val),
				ArrayDim: mmDollar[2].arr,
			}
		}
	case 67:
		mmDollar = mmS[mmpt-0 : mmpt+1]
		{
			mmVAL.par_tuple = paramsTuple{
				Present: false,
				Ins:     new(InParams),
				Outs:    new(OutParams),
			}
		}
	case 68:
		mmDollar = mmS[mmpt-6 : mmpt+1]
		{
			mmVAL.par_tuple = paramsTuple{
				Present: true,
				Ins:     mmDollar[4].i_params,
				Outs:    mmDollar[5].o_params,
			}
		}
	case 69:
		mmDollar = mmS[mmpt-5 : mmpt+1]
		{
			mmVAL.par_tuple = paramsTuple{
				Present: true,
				Ins:     mmDollar[3].i_params,
				Outs:    mmDollar[4].o_params,
			}
		}
	case 70:
		mmDollar = mmS[mmpt-4 : mmpt+1]
		{
			mmVAL.retstm = &ReturnStm{
				Node:     NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Bindings: mmDollar[3].bindings,
			}
		}
	case 71:
		mmDollar = mmS[mmpt-0 : mmpt+1]
		{
			mmVAL.plretains = nil
		}
	case 72:
		mmDollar = mmS[mmpt-4 : mmpt+1]
		{
			mmVAL.plretains = &PipelineRetains{
				Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Refs: mmDollar[3].reflist,
			}
		}
	case 73:
		mmDollar = mmS[mmpt-0 : mmpt+1]
		{
			mmVAL.reflist = nil
		}
	case 74:
		mmDollar = mmS[mmpt-3 : mmpt+1]
		{
			mmVAL.reflist = append(mmDollar[1].reflist, mmDollar[2].rexp)
		}
	case 75:
		mmDollar = mmS[mmpt-2 : mmpt+1]
		{
			mmVAL.calls = append(mmDollar[1].calls, mmDollar[2].call)
		}
	case 76:
		mmDollar = mmS[mmpt-1 : mmpt+1]
		{
			mmVAL.calls = []*CallStm{mmDollar[1].call}
		}
	case 77:
		mmDollar = mmS[mmpt-6 : mmpt+1]
		{
			id := mmDollar[3].intern.Get(mmDollar[3].val)
			mmVAL.call = &CallStm{
				Node:      NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Modifiers: mmDollar[2].modifiers,
				Id:        id,
				DecId:     id,
				Bindings:  mmDollar[5].bindings,
			}
		}
	case 78:
		mmDollar = mmS[mmpt-8 : mmpt+1]
		{
			mmVAL.call = &CallStm{
				Node:      NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Modifiers: mmDollar[2].modifiers,
				Id:        mmDollar[5].intern.Get(mmDollar[5].val),
				DecId:     mmDollar[3].intern.Get(mmDollar[3].val),
				Bindings:  mmDollar[7].bindings,
			}
		}
	case 79:
		mmDollar = mmS[mmpt-6 : mmpt+1]
		{
			id := mmDollar[3].intern.Get(mmDollar[3].val)
			mmVAL.call = &CallStm{
				Node:      NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Modifiers: new(Modifiers),
				Id:        id,
				DecId:     id,
				Bindings:  mmDollar[5].bindings,
				Mapping:   &mapSourcePlaceholder,
			}
		}
	case 80:
		mmDollar = mmS[mmpt-8 : mmpt+1]
		{
			mmVAL.call = &CallStm{
				Node:      NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Modifiers: new(Modifiers),
				Id:        mmDollar[5].intern.Get(mmDollar[5].val),
				DecId:     mmDollar[3].intern.Get(mmDollar[3].val),
				Bindings:  mmDollar[7].bindings,
				Mapping:   &mapSourcePlaceholder,
			}
		}
	case 81:
		mmDollar = mmS[mmpt-5 : mmpt+1]
		{
			mmDollar[1].call.Modifiers.Bindings = mmDollar[4].bindings
			mmVAL.call = mmDollar[1].call
		}
	case 82:
		mmDollar = mmS[mmpt-0 : mmpt+1]
		{
			mmVAL.modifiers = new(Modifiers)
		}
	case 83:
		mmDollar = mmS[mmpt-2 : mmpt+1]
		{
			mmVAL.modifiers.Local = true
		}
	case 84:
		mmDollar = mmS[mmpt-2 : mmpt+1]
		{
			mmVAL.modifiers.Preflight = true
		}
	case 85:
		mmDollar = mmS[mmpt-2 : mmpt+1]
		{
			mmVAL.modifiers.Volatile = true
		}
	case 86:
		mmDollar = mmS[mmpt-0 : mmpt+1]
		{
			mmVAL.bindings = &BindStms{
				Node: NewAstNode(mmDollar[0].loc, mmDollar[0].srcfile),
			}
		}
	case 87:
		mmDollar = mmS[mmpt-2 : mmpt+1]
		{
			mmDollar[1].bindings.List = append(mmDollar[1].bindings.List, mmDollar[2].binding)
			mmVAL.bindings = mmDollar[1].bindings
		}
	case 88:
		mmDollar = mmS[mmpt-4 : mmpt+1]
		{
			mmVAL.binding = &BindStm{
				Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Id:   local,
				Exp:  mmDollar[3].vexp,
			}
		}
	case 89:
		mmDollar = mmS[mmpt-4 : mmpt+1]
		{
			mmVAL.binding = &BindStm{
				Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Id:   preflight,
				Exp:  mmDollar[3].vexp,
			}
		}
	case 90:
		mmDollar = mmS[mmpt-4 : mmpt+1]
		{
			mmVAL.binding = &BindStm{
				Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Id:   volatile,
				Exp:  mmDollar[3].vexp,
			}
		}
	case 91:
		mmDollar = mmS[mmpt-4 : mmpt+1]
		{
			mmVAL.binding = &BindStm{
				Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Id:   disabled,
				Exp:  mmDollar[3].rexp,
			}
		}
	case 92:
		mmDollar = mmS[mmpt-2 : mmpt+1]
		{
			mmDollar[1].bindings.List = append(mmDollar[1].bindings.List, mmDollar[2].binding)
			mmVAL.bindings = mmDollar[1].bindings
		}
	case 93:
		mmDollar = mmS[mmpt-1 : mmpt+1]
		{
			mmVAL.bindings = &BindStms{
				Node: NewAstNode(mmDollar[0].loc, mmDollar[0].srcfile),
				List: []*BindStm{mmDollar[1].binding},
			}
		}
	case 95:
		mmDollar = mmS[mmpt-0 : mmpt+1]
		{
			mmVAL.bindings = &BindStms{
				Node: NewAstNode(mmDollar[0].loc, mmDollar[0].srcfile),
			}
		}
	case 96:
		mmDollar = mmS[mmpt-1 : mmpt+1]
		{
			mmVAL.bindings = &BindStms{
				Node: NewAstNode(mmDollar[0].loc, mmDollar[0].srcfile),
				List: []*BindStm{mmDollar[1].binding},
			}
		}
	case 97:
		mmDollar = mmS[mmpt-2 : mmpt+1]
		{
			mmDollar[1].bindings.List = append(mmDollar[1].bindings.List, mmDollar[2].binding)
			mmVAL.bindings = mmDollar[1].bindings
		}
	case 98:
		mmDollar = mmS[mmpt-2 : mmpt+1]
		{
			mmDollar[1].bindings.List = append(mmDollar[1].bindings.List, mmDollar[2].binding)
			mmVAL.bindings = mmDollar[1].bindings
		}
	case 99:
		mmDollar = mmS[mmpt-2 : mmpt+1]
		{
			mmDollar[1].bindings.List = append(mmDollar[1].bindings.List, mmDollar[2].binding)
			mmVAL.bindings = mmDollar[1].bindings
		}
	case 100:
		mmDollar = mmS[mmpt-4 : mmpt+1]
		{
			mmVAL.binding = &BindStm{
				Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Id:   mmDollar[1].intern.Get(mmDollar[1].val),
				Exp:  mmDollar[3].exp,
			}
		}
	case 101:
		mmDollar = mmS[mmpt-5 : mmpt+1]
		{
			mmVAL.binding = &BindStm{
				Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Id:   mmDollar[1].intern.Get(mmDollar[1].val),
				Exp: &SplitExp{
					valExp: valExp{Node: NewAstNode(mmDollar[3].loc, mmDollar[3].srcfile)},
					Value:  mmDollar[4].vexp,
					Source: mmDollar[4].vexp.(MapCallSource),
				},
			}
		}
	case 102:
		mmDollar = mmS[mmpt-5 : mmpt+1]
		{
			mmVAL.binding = &BindStm{
				Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Id:   mmDollar[1].intern.Get(mmDollar[1].val),
				Exp: &SplitExp{
					valExp: valExp{Node: NewAstNode(mmDollar[3].loc, mmDollar[3].srcfile)},
					Value:  mmDollar[4].vexp,
					Source: mmDollar[4].vexp.(MapCallSource),
				},
			}
		}
	case 103:
		mmDollar = mmS[mmpt-5 : mmpt+1]
		{
			mmVAL.binding = &BindStm{
				Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Id:   mmDollar[1].intern.Get(mmDollar[1].val),
				Exp: &SplitExp{
					valExp: valExp{Node: NewAstNode(mmDollar[3].loc, mmDollar[3].srcfile)},
					Value:  mmDollar[4].rexp,
				},
			}
		}
	case 104:
		mmDollar = mmS[mmpt-3 : mmpt+1]
		{
			mmVAL.exps = append(mmDollar[1].exps, mmDollar[3].exp)
		}
	case 105:
		mmDollar = mmS[mmpt-1 : mmpt+1]
		{
			mmVAL.exps = []Exp{mmDollar[1].exp}
		}
	case 106:
		mmDollar = mmS[mmpt-5 : mmpt+1]
		{
			mmDollar[1].kvpairs[unquote(mmDollar[3].val)] = mmDollar[5].exp
			mmVAL.kvpairs = mmDollar[1].kvpairs
		}
	case 107:
		mmDollar = mmS[mmpt-3 : mmpt+1]
		{
			mmVAL.kvpairs = map[string]Exp{unquote(mmDollar[1].val): mmDollar[3].exp}
		}
	case 108:
		mmDollar = mmS[mmpt-5 : mmpt+1]
		{
			mmDollar[1].kvpairs[mmDollar[3].intern.Get(mmDollar[3].val)] = mmDollar[5].exp
			mmVAL.kvpairs = mmDollar[1].kvpairs
		}
	case 109:
		mmDollar = mmS[mmpt-3 : mmpt+1]
		{
			mmVAL.kvpairs = map[string]Exp{mmDollar[1].intern.Get(mmDollar[1].val): mmDollar[3].exp}
		}
	case 110:
		mmDollar = mmS[mmpt-1 : mmpt+1]
		{
			mmVAL.exp = mmDollar[1].vexp
		}
	case 111:
		mmDollar = mmS[mmpt-1 : mmpt+1]
		{
			mmVAL.exp = mmDollar[1].rexp
		}
	case 112:
		mmDollar = mmS[mmpt-1 : mmpt+1]
		{ // Lexer guarantees parseable float strings.
			f := parseFloat(mmDollar[1].val)
			mmVAL.vexp = &FloatExp{
				valExp: valExp{Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile)},
				Value:  f,
			}
		}
	case 113:
		mmDollar = mmS[mmpt-1 : mmpt+1]
		{ // Lexer guarantees parseable int strings.
			i := parseInt(mmDollar[1].val)
			mmVAL.vexp = &IntExp{
				valExp: valExp{Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile)},
				Value:  i,
			}
		}
	case 114:
		mmDollar = mmS[mmpt-1 : mmpt+1]
		{
			mmVAL.vexp = &StringExp{
				valExp: valExp{Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile)},
				Kind:   KindString,
				Value:  unquote(mmDollar[1].val),
			}
		}
	case 118:
		mmDollar = mmS[mmpt-1 : mmpt+1]
		{
			mmVAL.vexp = &NullExp{
				valExp: valExp{Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile)},
			}
		}
	case 119:
		mmDollar = mmS[mmpt-3 : mmpt+1]
		{
			mmVAL.vexp = &ArrayExp{
				valExp: valExp{Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile)},
				Value:  mmDollar[2].exps,
			}
		}
	case 120:
		mmDollar = mmS[mmpt-4 : mmpt+1]
		{
			mmVAL.vexp = &ArrayExp{
				valExp: valExp{Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile)},
				Value:  mmDollar[2].exps,
			}
		}
	case 122:
		mmDollar = mmS[mmpt-2 : mmpt+1]
		{
			mmVAL.vexp = &ArrayExp{
				valExp: valExp{Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile)},
				Value:  make([]Exp, 0),
			}
		}
	case 123:
		mmDollar = mmS[mmpt-3 : mmpt+1]
		{
			mmVAL.vexp = &MapExp{
				valExp: valExp{Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile)},
				Kind:   KindMap,
				Value:  mmDollar[2].kvpairs,
			}
		}
	case 124:
		mmDollar = mmS[mmpt-4 : mmpt+1]
		{
			mmVAL.vexp = &MapExp{
				valExp: valExp{Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile)},
				Kind:   KindMap,
				Value:  mmDollar[2].kvpairs,
			}
		}
	case 126:
		mmDollar = mmS[mmpt-3 : mmpt+1]
		{
			mmVAL.vexp = &MapExp{
				valExp: valExp{Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile)},
				Kind:   KindStruct,
				Value:  mmDollar[2].kvpairs,
			}
		}
	case 127:
		mmDollar = mmS[mmpt-4 : mmpt+1]
		{
			mmVAL.vexp = &MapExp{
				valExp: valExp{Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile)},
				Kind:   KindStruct,
				Value:  mmDollar[2].kvpairs,
			}
		}
	case 128:
		mmDollar = mmS[mmpt-2 : mmpt+1]
		{
			mmVAL.vexp = &MapExp{
				valExp: valExp{Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile)},
				Kind:   KindMap,
				Value:  make(map[string]Exp, 0),
			}
		}
	case 129:
		mmDollar = mmS[mmpt-1 : mmpt+1]
		{
			mmVAL.vexp = &BoolExp{
				valExp: valExp{Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile)},
				Value:  true,
			}
		}
	case 130:
		mmDollar = mmS[mmpt-1 : mmpt+1]
		{
			mmVAL.vexp = &BoolExp{
				valExp: valExp{Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile)},
				Value:  false,
			}
		}
	case 131:
		mmDollar = mmS[mmpt-3 : mmpt+1]
		{
			mmVAL.rexp = &RefExp{
				Node:     NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Kind:     KindCall,
				Id:       mmDollar[1].intern.Get(mmDollar[1].val),
				OutputId: mmDollar[3].intern.Get(mmDollar[3].val),
			}
		}
	case 132:
		mmDollar = mmS[mmpt-3 : mmpt+1]
		{
			mmVAL.rexp = &RefExp{
				Node:     NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Kind:     KindCall,
				Id:       mmDollar[1].intern.Get(mmDollar[1].val),
				OutputId: defaultOutName,
			}
		}
	case 133:
		mmDollar = mmS[mmpt-1 : mmpt+1]
		{
			mmVAL.rexp = &RefExp{
				Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Kind: KindCall,
				Id:   mmDollar[1].intern.Get(mmDollar[1].val),
			}
		}
	case 134:
		mmDollar = mmS[mmpt-3 : mmpt+1]
		{
			mmVAL.rexp = &RefExp{
				Node: NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Kind: KindSelf,
				Id:   mmDollar[3].intern.Get(mmDollar[3].val),
			}
		}
	case 135:
		mmDollar = mmS[mmpt-5 : mmpt+1]
		{
			mmVAL.rexp = &RefExp{
				Node:     NewAstNode(mmDollar[1].loc, mmDollar[1].srcfile),
				Kind:     KindSelf,
				Id:       mmDollar[3].intern.Get(mmDollar[3].val),
				OutputId: mmDollar[5].intern.Get(mmDollar[5].val),
			}
		}
	}
	goto mmstack /* stack new state and value */
}
