name: golangci-lint
on:
  pull_request:

permissions:
  contents: read
  # Write permissions are required in order to produce annotations.
  checks: write

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.19"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50
          only-new-issues: true
          args: -c .github/.golangci.yml
