name: golangci-lint
on:
  pull_request:

permissions:
  contents: read
  # Write permissions are required in order to produce annotations.
  checks: write

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.23"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.63
          only-new-issues: true
          args: -c .github/.golangci.yml
